### ISSUE TITLE
Pls update your instruction

### ISSUE THREAD

**Issue by ForteDexe** [marioroy/nvidia-acceleration-on-ubuntu#1]
Some of it is outdated:
```
sudo tee /etc/modprobe.d/enable-nvidia-modeset.conf >/dev/null <<'EOF'
options nvidia-drm modeset=1
EOF

sudo update-initramfs -u -k all
```
-> My gdm cant boot after this command, so I rollback and skip this part instead.

```
git clone https://github.com/marioroy/nvaccel-on-ubuntu.git
cd nvaccel-on-ubuntu
```
-> git clone https://github.com/marioroy/nvidia-acceleration-on-ubuntu
cd nvidia-acceleration-on-ubuntu

```
sudo ./install-vivaldi
Please run the script as a normal user, exiting...
```
-> ./install-vivaldi

Btw: Your git is fucking awesome man, I was digging up the internet for 2days, and only your git worked. Thank you and your team very much.

**Comment by marioroy** [comment]
I updated the README file to skip the step if `nvidia-graphics-drivers-kms.conf` is present in `/etc/modprobe.d/`.
